### ISSUE TITLE
Invalid order Id

### ISSUE THREAD

**Issue by elreeda** [bokonon82/klarna-checkout#1]
Hi mate, thx for your awesome package which is helped me alot, but I faced one little problem which is when I try to check if the ID is valid or not, if its not valid i got stuck in timeout, when i checked your code,
I was wondering if you can add this tiny statement

> if (response.statusCode === 200) {
>                 return resolve(JSON.parse(body));
>               } else {
>                 return reject({status: 'not_found', message: 'This order ID not found.'});
>               }

in this [line of code](https://github.com/monkybrain/klarna-checkout/blob/master/src/klarna.js#L199)

**Comment by monkybrain** [comment]
Sorry for the late reply! Been quite busy lately and haven't used or updated this repo for ages so need to look through it again quickly but your suggestion seems reasonable. Would you care to send a PR? Got a couple more PRs yesterday from someone else so thought I'd dive into this repo again this afternoon.

**Comment by monkybrain** [comment]
@Reda-bx New version (1.3.0) now published with your suggestions included
